version: "3.7"
services: 
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: esavods
    container_name: esavods-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - esavods
  
  db:
    image: mysql:5.7
    container_name: esavods-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: prod
      SERVICE_NAME: mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ~/db/esavods:/var/lib/mysql
    networks:
      - esavods

  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: esavods-nginx
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: stewart.m.gordon@gmail.com
      STAGING: 1
      DEBUG: 1
    ports:
      - 80:80
      - 443:443
    volumes:
      # - ./:/var/www
      - ./docker-compose/nginx/prod:/etc/nginx/user_conf.d
      - ./nginx_secrets:/etc/letsencrypt
    networks:
      - esavods
      
networks:
  esavods:
    driver: bridge

volumes:
  nginx_secrets: